# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-06 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210629_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='default.jpeg', upload_to='articles/'),
        ),
    ]
